require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'iskoolu' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  pod 'SGActionView', :git => 'https://github.com/prscX/SGActionView.git'
  
  target 'iskooluTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end

  use_native_modules!

  pod 'RNImageHelper', :path => '../node_modules/react-native-image-helper/ios'
  pod 'RNBottomActionSheet', :path => '../node_modules/react-native-bottom-action-sheet/ios'
end

target 'iskoolu-tvOS' do
  # Pods for iskoolu-tvOS

  target 'iskoolu-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
